name: Publish MCAddons

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: release
      - name: 'Set up'
        run: |
          cd release
          file=(*.mcworld);[ -f "$file" ] && mv *.mcworld ../
          find -maxdepth 1 \! -regex '.* \(BP\|RP\)' -type f -delete
          find -maxdepth 1 \! -regex '.* \(BP\|RP\)' -type d -exec rm -r {} ';'
          cd ..
          ls
      - uses: vimtor/action-zip@v1
        with:
          files: release
          dest: release.mcaddon
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release.mcaddon
            *.mcworld
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}